// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1l-6K2zcvcDvinPBdGe9SPmsRM1E_uqk',
    appId: '1:796785179858:web:9926fd74ca554186ab010b',
    messagingSenderId: '796785179858',
    projectId: 'genzquest',
    authDomain: 'genzquest.firebaseapp.com',
    storageBucket: 'genzquest.appspot.com',
    measurementId: 'G-8M6W1SDXC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNv7zrLtWiBl_hOj2QMMpD_WfMdSCkrFI',
    appId: '1:796785179858:android:5e24343a894ce6e7ab010b',
    messagingSenderId: '796785179858',
    projectId: 'genzquest',
    storageBucket: 'genzquest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqZ0U3faLsENiN3A6BhxYIuikCrR3KDu4',
    appId: '1:796785179858:ios:21af6d7c24d40230ab010b',
    messagingSenderId: '796785179858',
    projectId: 'genzquest',
    storageBucket: 'genzquest.appspot.com',
    iosBundleId: 'com.example.genzquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqZ0U3faLsENiN3A6BhxYIuikCrR3KDu4',
    appId: '1:796785179858:ios:21af6d7c24d40230ab010b',
    messagingSenderId: '796785179858',
    projectId: 'genzquest',
    storageBucket: 'genzquest.appspot.com',
    iosBundleId: 'com.example.genzquest',
  );
}
